package com.briup.apps.cms.dao;

import com.briup.apps.cms.bean.Role_privilege;
import com.briup.apps.cms.bean.Role_privilegeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface Role_privilegeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_role_privilege
     *
     * @mbg.generated Mon Nov 11 20:05:17 CST 2019
     */
    long countByExample(Role_privilegeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_role_privilege
     *
     * @mbg.generated Mon Nov 11 20:05:17 CST 2019
     */
    int deleteByExample(Role_privilegeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_role_privilege
     *
     * @mbg.generated Mon Nov 11 20:05:17 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_role_privilege
     *
     * @mbg.generated Mon Nov 11 20:05:17 CST 2019
     */
    int insert(Role_privilege record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_role_privilege
     *
     * @mbg.generated Mon Nov 11 20:05:17 CST 2019
     */
    int insertSelective(Role_privilege record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_role_privilege
     *
     * @mbg.generated Mon Nov 11 20:05:17 CST 2019
     */
    List<Role_privilege> selectByExample(Role_privilegeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_role_privilege
     *
     * @mbg.generated Mon Nov 11 20:05:17 CST 2019
     */
    Role_privilege selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_role_privilege
     *
     * @mbg.generated Mon Nov 11 20:05:17 CST 2019
     */
    int updateByExampleSelective(@Param("record") Role_privilege record, @Param("example") Role_privilegeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_role_privilege
     *
     * @mbg.generated Mon Nov 11 20:05:17 CST 2019
     */
    int updateByExample(@Param("record") Role_privilege record, @Param("example") Role_privilegeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_role_privilege
     *
     * @mbg.generated Mon Nov 11 20:05:17 CST 2019
     */
    int updateByPrimaryKeySelective(Role_privilege record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_role_privilege
     *
     * @mbg.generated Mon Nov 11 20:05:17 CST 2019
     */
    int updateByPrimaryKey(Role_privilege record);
}