package com.briup.apps.cms.dao;

import com.briup.apps.cms.bean.User_role;
import com.briup.apps.cms.bean.User_roleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface User_roleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_user_role
     *
     * @mbg.generated Mon Nov 11 20:05:17 CST 2019
     */
    long countByExample(User_roleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_user_role
     *
     * @mbg.generated Mon Nov 11 20:05:17 CST 2019
     */
    int deleteByExample(User_roleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_user_role
     *
     * @mbg.generated Mon Nov 11 20:05:17 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_user_role
     *
     * @mbg.generated Mon Nov 11 20:05:17 CST 2019
     */
    int insert(User_role record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_user_role
     *
     * @mbg.generated Mon Nov 11 20:05:17 CST 2019
     */
    int insertSelective(User_role record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_user_role
     *
     * @mbg.generated Mon Nov 11 20:05:17 CST 2019
     */
    List<User_role> selectByExample(User_roleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_user_role
     *
     * @mbg.generated Mon Nov 11 20:05:17 CST 2019
     */
    User_role selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_user_role
     *
     * @mbg.generated Mon Nov 11 20:05:17 CST 2019
     */
    int updateByExampleSelective(@Param("record") User_role record, @Param("example") User_roleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_user_role
     *
     * @mbg.generated Mon Nov 11 20:05:17 CST 2019
     */
    int updateByExample(@Param("record") User_role record, @Param("example") User_roleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_user_role
     *
     * @mbg.generated Mon Nov 11 20:05:17 CST 2019
     */
    int updateByPrimaryKeySelective(User_role record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_user_role
     *
     * @mbg.generated Mon Nov 11 20:05:17 CST 2019
     */
    int updateByPrimaryKey(User_role record);
}